var express = require("express");

var ensureAuthenticated = require("../../auth/auth").ensureAuthenticated;

var Post = require("../../models/post");
var Inspection = require("../../models/inspection");


var router = express.Router();

router.use(ensureAuthenticated);// ensures that all routes in this route are now authenticated

router.get("/", function(req, res){ // implicit /post before each of these routes
    Post.find({userID:req.user._id}).exec(function(err, posts){ // find in database
        if(err){console.log(err);}
        res.render("post/posts", {posts:posts}); // passing on the posts that were found matching the userID
    });
 });

 router.get("/add", function(req, res){
    res.render("post/addpost");
 });


 router.post("/add", function(req, res){ // when an 'add' request is made by the html button

    var newPost = new Post({
        title:req.body.title,
        content:req.body.content,
        userID:req.user._id // _id is generated by mongoDB for each user
    });

    newPost.save(function(err,post){ // save post to database
        if(err){console.log(err);}
        res.redirect("/posts"); // after making a post, go to the posts page
    });
 });

 // localhost:3000/posts/12345 --> fetch the post with id 12345
router.get("/:postId", function(req,res){ // :postID represents a variable parameter as a route
    Post.findById(req.params.postId).exec(function(err, post){
        res.render("post/detailpost",{post:post});
    });
});

router.get("/edit/:postId", function(req,res){ // :postID represents a variable parameter as a route
    Post.findById(req.params.postId).exec(function(err, post){
        res.render("post/editpost",{post:post});
    });
});

router.post("/update", async function(req, res){
    // find the existing post in the database
    const post = await Post.findById(req.body.postid);

    //update post data
    post.title = req.body.title;
    post.content = req.body.content;

    // asynchronous save
    try {
        let savePost = await post.save(); // save post to database
        res.redirect("/posts/" + req.body.postid);  // go back to post page

    } catch (err) {
        res.status(500).send(err);
    }
//change
});


module.exports = router;