var express = require("express");
var ensureAuthenticated = require("../../auth/auth").ensureAuthenticated;

var router = express.Router();
var Post = require("../../models/post")
router.use(ensureAuthenticated); // ensures that all routes in this route are now authenticated

// the posts route is in this seperate file so that it can be authenticated.
router.get("/", function(req, res){
    Post.find({userID:req.user._id}).exec(function(err,posts){
        if(err){console.log(err);}
        res.render("post/posts", {posts:posts}) // passing on the posts that were found matching the userID
    });
});

router.get("/add", function(req, res){
    res.render("post/addpost");
});

router.post("/add", function(req, res){
    var newPost = new Post({
        title:req.body.title,
        content:req.body.content,
        userID:req.user._id // _id is generated by mongoDB for each user 
    });

    newPost.save(function(err, post){ // save post to database
        if(err){console.log(err);}
        res.redirect("/posts"); // after making a post, go to the posts page
    });
});


module.exports = router;